// eslint-disable-next-line no-unused-vars
const reservedCPP = [
  { id: 49, value: 'int', category: 'data type' },
  { id: 50, value: 'double', category: 'data type' },
  { id: 51, value: 'char', category: 'data type' },
  { id: 52, value: 'bool', category: 'data type' },
  { id: 53, value: 'float', category: 'data type' },
  { id: 54, value: 'if', category: 'control flow' },
  { id: 55, value: 'else', category: 'control flow' },
  { id: 56, value: 'switch', category: 'control flow' },
  { id: 57, value: 'case', category: 'control flow' },
  { id: 58, value: 'default', category: 'control flow' },
  { id: 59, value: 'while', category: 'control flow' },
  { id: 60, value: 'do', category: 'control flow' },
  { id: 61, value: 'for', category: 'control flow' },
  { id: 62, value: 'break', category: 'control flow' },
  { id: 63, value: 'continue', category: 'control flow' },
  { id: 64, value: 'return', category: 'control flow' },
  { id: 65, value: 'void', category: 'functions' },
  { id: 66, value: 'auto', category: 'functions' },
  { id: 67, value: 'const', category: 'functions' },
  { id: 68, value: 'static', category: 'functions' },
  { id: 69, value: 'inline', category: 'functions' },
  { id: 70, value: 'extern', category: 'functions' },
  { id: 71, value: 'register', category: 'functions' },
  { id: 72, value: 'virtual', category: 'functions' },
  { id: 73, value: 'class', category: 'object-oriented' },
  { id: 74, value: 'public', category: 'object-oriented' },
  { id: 75, value: 'private', category: 'object-oriented' },
  { id: 76, value: 'protected', category: 'object-oriented' },
  { id: 77, value: 'friend', category: 'object-oriented' },
  { id: 78, value: 'virtual', category: 'object-oriented' },
  { id: 79, value: 'new', category: 'object-oriented' },
  { id: 80, value: 'delete', category: 'object-oriented' },
  { id: 81, value: 'this', category: 'object-oriented' },
  { id: 82, value: 'new', category: 'memory management' },
  { id: 83, value: 'delete', category: 'memory management' },
  { id: 84, value: 'try', category: 'exception handling' },
  { id: 85, value: 'catch', category: 'exception handling' },
  { id: 86, value: 'throw', category: 'exception handling' },
  { id: 87, value: 'const', category: 'modifiers' },
  { id: 88, value: 'volatile', category: 'modifiers' },
  { id: 89, value: 'mutable', category: 'modifiers' },
  { id: 90, value: 'explicit', category: 'modifiers' },
  { id: 91, value: 'namespace', category: 'namespace' },
  { id: 92, value: 'template', category: 'namespace' },
  { id: 93, value: 'typename', category: 'namespace' },
  { id: 94, value: 'class', category: 'namespace' },
  { id: 95, value: 'const', category: 'type qualifier' },
  { id: 96, value: 'volatile', category: 'type qualifier' },
  { id: 97, value: 'mutable', category: 'type qualifier' }];

export default reservedCPP;
