// eslint-disable-next-line no-unused-vars
const reservedJava = [
  { id: 1, value: 'if', category: 'control flow' },
  { id: 2, value: 'else', category: 'control flow' },
  { id: 3, value: 'switch', category: 'control flow' },
  { id: 4, value: 'case', category: 'control flow' },
  { id: 5, value: 'default', category: 'control flow' },
  { id: 6, value: 'while', category: 'control flow' },
  { id: 7, value: 'do', category: 'control flow' },
  { id: 8, value: 'for', category: 'control flow' },
  { id: 9, value: 'break', category: 'control flow' },
  { id: 10, value: 'continue', category: 'control flow' },
  { id: 11, value: 'return', category: 'control flow' },
  { id: 12, value: 'class', category: 'object-oriented' },
  { id: 13, value: 'interface', category: 'object-oriented' },
  { id: 14, value: 'extends', category: 'object-oriented' },
  { id: 15, value: 'implements', category: 'object-oriented' },
  { id: 16, value: 'new', category: 'object-oriented' },
  { id: 17, value: 'this', category: 'object-oriented' },
  { id: 18, value: 'super', category: 'object-oriented' },
  { id: 19, value: 'abstract', category: 'object-oriented' },
  { id: 20, value: 'final', category: 'object-oriented' },
  { id: 21, value: 'static', category: 'object-oriented' },
  { id: 22, value: 'private', category: 'object-oriented' },
  { id: 23, value: 'protected', category: 'object-oriented' },
  { id: 24, value: 'public', category: 'object-oriented' },
  { id: 25, value: 'boolean', category: 'data types' },
  { id: 26, value: 'byte', category: 'data types' },
  { id: 27, value: 'short', category: 'data types' },
  { id: 28, value: 'int', category: 'data types' },
  { id: 29, value: 'long', category: 'data types' },
  { id: 30, value: 'float', category: 'data types' },
  { id: 31, value: 'double', category: 'data types' },
  { id: 32, value: 'char', category: 'data types' },
  { id: 33, value: 'try', category: 'exception handling' },
  { id: 34, value: 'catch', category: 'exception handling' },
  { id: 35, value: 'finally', category: 'exception handling' },
  { id: 36, value: 'throw', category: 'exception handling' },
  { id: 37, value: 'throws', category: 'exception handling' }];

export default reservedJava;
