const reservedPython = [
  { id: 1, value: 'if', category: 'control flow' },
  { id: 2, value: 'elif', category: 'control flow' },
  { id: 3, value: 'else', category: 'control flow' },
  { id: 4, value: 'while', category: 'control flow' },
  { id: 5, value: 'for', category: 'control flow' },
  { id: 6, value: 'break', category: 'control flow' },
  { id: 7, value: 'continue', category: 'control flow' },
  { id: 8, value: 'and', category: 'control flow' },
  { id: 9, value: 'or', category: 'control flow' },
  { id: 10, value: 'not', category: 'control flow' },
  { id: 11, value: 'def', category: 'function' },
  { id: 12, value: 'return', category: 'function' },
  { id: 13, value: 'yield', category: 'function' },
  { id: 14, value: 'class', category: 'object oriented' },
  { id: 15, value: 'try', category: 'exception handling' },
  { id: 16, value: 'except', category: 'exception handling' },
  { id: 17, value: 'finally', category: 'exception handling' },
  { id: 18, value: 'raise', category: 'exception handling' },
  { id: 19, value: 'assert', category: 'exception handling' },
  { id: 20, value: 'import', category: 'modules' },
  { id: 21, value: 'from', category: 'modules' },
  { id: 22, value: 'as', category: 'modules' },
  { id: 23, value: 'global', category: 'modules' },
  { id: 24, value: 'nonlocal', category: 'modules' },
  { id: 25, value: 'None', category: 'others' },
  { id: 26, value: 'in', category: 'others' },
  { id: 27, value: 'is', category: 'others' },
  { id: 28, value: 'lambda', category: 'others' }];

export default reservedPython;
