const reservedPython = [{ value: 'if', category: 'control flow' },
  { value: 'elif', category: 'control flow' },
  { value: 'else', category: 'control flow' },
  { value: 'while', category: 'control flow' },
  { value: 'for', category: 'control flow' },
  { value: 'break', category: 'control flow' },
  { value: 'continue', category: 'control flow' },
  { value: 'and', category: 'control flow' },
  { value: 'or', category: 'control flow' },
  { value: 'not', category: 'control flow' },
  { value: 'def', category: 'function' },
  { value: 'return', category: 'function' },
  { value: 'yield', category: 'function' },
  { value: 'class', category: 'object oriented' },
  { value: 'try', category: 'exception handling' },
  { value: 'except', category: 'exception handling' },
  { value: 'finally', category: 'exception handling' },
  { value: 'raise', category: 'exception handling' },
  { value: 'assert', category: 'exception handling' },
  { value: 'import', category: 'modules' },
  { value: 'from', category: 'modules' },
  { value: 'as', category: 'modules' },
  { value: 'global', category: 'modules' },
  { value: 'nonlocal', category: 'modules' },
  { value: 'None', category: 'others' },
  { value: 'in', category: 'others' },
  { value: 'is', category: 'others' },
  { value: 'lambda', category: 'others' }];

export default reservedPython;
